set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()


Plugin 'VundleVim/Vundle.vim'

" snippets common

Plugin 'honza/vim-snippets'

" ultisnips
Plugin 'SirVer/ultisnips'

" snipmate
"Plugin 'MarcWeber/vim-addon-mw-utils'
"Plugin 'tomtom/tlib_vim'
"Plugin 'garbas/vim-snipmate'


Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdTree'
Plugin 'jwalton512/vim-blade'
Plugin 'easymotion/vim-easymotion'
Plugin 'tmhedberg/matchit'
Plugin 'tpope/vim-surround'

Bundle 'gosukiwi/vim-atom-dark'


call vundle#end()            " required

filetype plugin indent on    " required
let mapleader = ","

" my own preferences
source ~/dotfiles/vim/settings/basic.vim
source ~/dotfiles/vim/settings/mappings.vim
source ~/dotfiles/vim/settings/appearance.vim
source ~/dotfiles/vim/settings/plugins.vim

